export enum Permissions {
  // Catalog Management
  VIEW_PRODUCTS = "VIEW_PRODUCTS",
  CREATE_PRODUCTS = "CREATE_PRODUCTS",
  EDIT_PRODUCTS = "EDIT_PRODUCTS",
  DELETE_PRODUCTS = "DELETE_PRODUCTS",

  VIEW_VARIANTS = "VIEW_VARIANTS",
  CREATE_VARIANTS = "CREATE_VARIANTS",
  EDIT_VARIANTS = "EDIT_VARIANTS",
  DELETE_VARIANTS = "DELETE_VARIANTS",

  VIEW_ATTRIBUTES = "VIEW_ATTRIBUTES",
  MANAGE_ATTRIBUTES = "MANAGE_ATTRIBUTES",

  VIEW_OPTION_TYPES = "VIEW_OPTION_TYPES",
  MANAGE_OPTION_TYPES = "MANAGE_OPTION_TYPES",

  // Categories & Navigation
  VIEW_TAXONOMIES = "VIEW_TAXONOMIES",
  MANAGE_TAXONOMIES = "MANAGE_TAXONOMIES",
  VIEW_TAXONS = "VIEW_TAXONS",
  MANAGE_TAXONS = "MANAGE_TAXONS",

  // Content Management
  VIEW_BILLBOARDS = "VIEW_BILLBOARDS",
  MANAGE_BILLBOARDS = "MANAGE_BILLBOARDS",

  VIEW_COLORS = "VIEW_COLORS",
  MANAGE_COLORS = "MANAGE_COLORS",

  VIEW_SIZES = "VIEW_SIZES",
  MANAGE_SIZES = "MANAGE_SIZES",

  // Order Management
  VIEW_ORDERS = "VIEW_ORDERS",
  MANAGE_ORDERS = "MANAGE_ORDERS",

  // Inventory Management
  VIEW_STOCK = "VIEW_STOCK",
  MANAGE_STOCK = "MANAGE_STOCK",
  VIEW_STOCK_MOVEMENTS = "VIEW_STOCK_MOVEMENTS",
  MANAGE_STOCK_MOVEMENTS = "MANAGE_STOCK_MOVEMENTS",

  // Customer Management
  VIEW_CUSTOMERS = "VIEW_CUSTOMERS",
  MANAGE_CUSTOMERS = "MANAGE_CUSTOMERS",

  // Supplier Management
  VIEW_SUPPLIERS = "VIEW_SUPPLIERS",
  MANAGE_SUPPLIERS = "MANAGE_SUPPLIERS",

  // Analytics & Reviews
  VIEW_ANALYTICS = "VIEW_ANALYTICS",
  MANAGE_ANALYTICS = "MANAGE_ANALYTICS",
  VIEW_REVIEWS = "VIEW_REVIEWS",
  MANAGE_REVIEWS = "MANAGE_REVIEWS",

  // Store Management
  VIEW_SETTINGS = "VIEW_SETTINGS",
  MANAGE_SETTINGS = "MANAGE_SETTINGS",
  VIEW_STORE = "VIEW_STORE",
  MANAGE_STORE = "MANAGE_STORE",

  // Staff & Roles Management
  VIEW_STAFF = "VIEW_STAFF",
  MANAGE_STAFF = "MANAGE_STAFF",
  VIEW_ROLES = "VIEW_ROLES",
  MANAGE_ROLES = "MANAGE_ROLES",

  // Brand Management
  VIEW_BRANDS = "VIEW_BRANDS",
  MANAGE_BRANDS = "MANAGE_BRANDS",

  // Layout Management
  VIEW_LAYOUTS = "VIEW_LAYOUTS",
  MANAGE_LAYOUTS = "MANAGE_LAYOUTS",

  // Documentation Access
  VIEW_DOCUMENTATION = "VIEW_DOCUMENTATION"
}
